baseURL = 'https://artibrains.github.io/'
title = 'Artificial Brains Trilogy'
theme = 'hugo-theme-relearn'

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = false
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          inline = [['\\(', '\\)'], ['$', '$']]
          block  = [['\\[', '\\]'], ['$$', '$$']]
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = 'github'
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[security]
  enableInlineShortcodes = true
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^pandoc$', '^asciidoctor$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

[caches]
  [caches.images]
    dir = ':cacheDir/images'


# Configuración multilingüe
defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false

[languages]
  [languages.es]
    languageName = 'Español'
    weight = 1
    title = 'Trilogía Cerebros Artificiales'
    contentDir = 'content'

  [languages.en]
    languageName = 'English'
    weight = 2
    title = 'Artificial Brains Trilogy'
    contentDir = 'content'

[params]
  themeVariant = ['auto','zen-light', 'zen-dark']
    themeVariantAuto = ['zen-light', 'zen-dark']

  # Mostrar selector de idiomas
  showLanguageSwitcher = true
  alwaysopen = true
  disableSearch = true
  
  # Enable math rendering globally
  math = true

